package train.oracle.apps.ak.ak18726.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class groupLovAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public groupLovAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("train.oracle.apps.ak.ak18726.lov.server", /* package name */
      "groupLovAMLocal" /* Configuration Name */);
    }

    /**Container's getter for groupLovVO1
     */
    public groupLovVOImpl getgroupLovVO1() {
        return (groupLovVOImpl)findViewObject("groupLovVO1");
    }
}
