package train.oracle.apps.ak.ak18726.poplist.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class poplistAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public poplistAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("train.oracle.apps.ak.ak18726.poplist.server", /* package name */
      "poplistAMLocal" /* Configuration Name */);
    }

    /**Container's getter for poplistVO1
     */
    public poplistVOImpl getpoplistVO1() {
        return (poplistVOImpl)findViewObject("poplistVO1");
    }
}
