package train.oracle.apps.ak.ak18726.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class testBodyVORowImpl extends OAViewRowImpl {
    public static final int YITEMNO = 0;
    public static final int ITEMNAME = 1;
    public static final int MONTHSPURCHASEPRICE6 = 2;
    public static final int TOOLNO = 3;
    public static final int SPEC = 4;
    public static final int SUPPLIERCODE = 5;
    public static final int MAKERCODE = 6;
    public static final int CURRENCYCODE = 7;
    public static final int PROCUREMENTGROUPCODE = 8;
    public static final int PROCUREMENTPERSONCODE = 9;
    public static final int SUPPLIERID = 10;
    public static final int MAKERID = 11;
    public static final int MFGMAKERID = 12;

    /**This is the default constructor (do not remove)
     */
    public testBodyVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute YItemNo
     */
    public String getYItemNo() {
        return (String) getAttributeInternal(YITEMNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute YItemNo
     */
    public void setYItemNo(String value) {
        setAttributeInternal(YITEMNO, value);
    }

    /**Gets the attribute value for the calculated attribute ItemName
     */
    public String getItemName() {
        return (String) getAttributeInternal(ITEMNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ItemName
     */
    public void setItemName(String value) {
        setAttributeInternal(ITEMNAME, value);
    }

    /**Gets the attribute value for the calculated attribute MonthsPurchasePrice6
     */
    public Number getMonthsPurchasePrice6() {
        return (Number) getAttributeInternal(MONTHSPURCHASEPRICE6);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MonthsPurchasePrice6
     */
    public void setMonthsPurchasePrice6(Number value) {
        setAttributeInternal(MONTHSPURCHASEPRICE6, value);
    }

    /**Gets the attribute value for the calculated attribute ToolNo
     */
    public String getToolNo() {
        return (String) getAttributeInternal(TOOLNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ToolNo
     */
    public void setToolNo(String value) {
        setAttributeInternal(TOOLNO, value);
    }

    /**Gets the attribute value for the calculated attribute Spec
     */
    public String getSpec() {
        return (String) getAttributeInternal(SPEC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Spec
     */
    public void setSpec(String value) {
        setAttributeInternal(SPEC, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierCode
     */
    public String getSupplierCode() {
        return (String) getAttributeInternal(SUPPLIERCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierCode
     */
    public void setSupplierCode(String value) {
        setAttributeInternal(SUPPLIERCODE, value);
    }

    /**Gets the attribute value for the calculated attribute MakerCode
     */
    public String getMakerCode() {
        return (String) getAttributeInternal(MAKERCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MakerCode
     */
    public void setMakerCode(String value) {
        setAttributeInternal(MAKERCODE, value);
    }

    /**Gets the attribute value for the calculated attribute CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**Gets the attribute value for the calculated attribute ProcurementGroupCode
     */
    public String getProcurementGroupCode() {
        return (String) getAttributeInternal(PROCUREMENTGROUPCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProcurementGroupCode
     */
    public void setProcurementGroupCode(String value) {
        setAttributeInternal(PROCUREMENTGROUPCODE, value);
    }

    /**Gets the attribute value for the calculated attribute ProcurementPersonCode
     */
    public String getProcurementPersonCode() {
        return (String) getAttributeInternal(PROCUREMENTPERSONCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProcurementPersonCode
     */
    public void setProcurementPersonCode(String value) {
        setAttributeInternal(PROCUREMENTPERSONCODE, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierId
     */
    public Number getSupplierId() {
        return (Number) getAttributeInternal(SUPPLIERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierId
     */
    public void setSupplierId(Number value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**Gets the attribute value for the calculated attribute MakerId
     */
    public Number getMakerId() {
        return (Number) getAttributeInternal(MAKERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MakerId
     */
    public void setMakerId(Number value) {
        setAttributeInternal(MAKERID, value);
    }

    /**Gets the attribute value for the calculated attribute MfgMakerId
     */
    public Number getMfgMakerId() {
        return (Number) getAttributeInternal(MFGMAKERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MfgMakerId
     */
    public void setMfgMakerId(Number value) {
        setAttributeInternal(MFGMAKERID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case YITEMNO:
            return getYItemNo();
        case ITEMNAME:
            return getItemName();
        case MONTHSPURCHASEPRICE6:
            return getMonthsPurchasePrice6();
        case TOOLNO:
            return getToolNo();
        case SPEC:
            return getSpec();
        case SUPPLIERCODE:
            return getSupplierCode();
        case MAKERCODE:
            return getMakerCode();
        case CURRENCYCODE:
            return getCurrencyCode();
        case PROCUREMENTGROUPCODE:
            return getProcurementGroupCode();
        case PROCUREMENTPERSONCODE:
            return getProcurementPersonCode();
        case SUPPLIERID:
            return getSupplierId();
        case MAKERID:
            return getMakerId();
        case MFGMAKERID:
            return getMfgMakerId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case YITEMNO:
            setYItemNo((String)value);
            return;
        case ITEMNAME:
            setItemName((String)value);
            return;
        case MONTHSPURCHASEPRICE6:
            setMonthsPurchasePrice6((Number)value);
            return;
        case TOOLNO:
            setToolNo((String)value);
            return;
        case SPEC:
            setSpec((String)value);
            return;
        case SUPPLIERCODE:
            setSupplierCode((String)value);
            return;
        case MAKERCODE:
            setMakerCode((String)value);
            return;
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        case PROCUREMENTGROUPCODE:
            setProcurementGroupCode((String)value);
            return;
        case PROCUREMENTPERSONCODE:
            setProcurementPersonCode((String)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case MAKERID:
            setMakerId((Number)value);
            return;
        case MFGMAKERID:
            setMfgMakerId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
