package train.oracle.apps.ak.ak18726.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class testHeadVORowImpl extends OAViewRowImpl {

    public static final int BEGINNINGCARRYINGOVERID = 0;
    public static final int APPRICABLEPERIODFROM = 1;
    public static final int APPRICABLEPERIODTO = 2;
    public static final int VOSTATUS = 3;
    public static final int PROCUREMENTGROUPCODE = 4;
    public static final int PROCUREMENTPERSONCODE = 5;
    public static final int SUPPLIERCODE = 6;
    public static final int SUPPLIERNAME = 7;
    public static final int VOCOUNTNUM = 8;
    public static final int VOSUBCONTRACTACTCLS = 9;
    public static final int SUMAMOUNT = 10;
    public static final int MAKERCODE = 11;
    public static final int MAKERNAME = 12;
    public static final int CURRENCYCODE = 13;
    public static final int SUPPLIERID = 14;
    public static final int MAKERID = 15;

    /**This is the default constructor (do not remove)
     */
    public testHeadVORowImpl() {
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BEGINNINGCARRYINGOVERID:
            return getBeginningCarryingoverId();
        case APPRICABLEPERIODFROM:
            return getAppricablePeriodFrom();
        case APPRICABLEPERIODTO:
            return getAppricablePeriodTo();
        case VOSTATUS:
            return getVoStatus();
        case PROCUREMENTGROUPCODE:
            return getProcurementGroupCode();
        case PROCUREMENTPERSONCODE:
            return getProcurementPersonCode();
        case SUPPLIERCODE:
            return getSupplierCode();
        case SUPPLIERNAME:
            return getSupplierName();
        case VOCOUNTNUM:
            return getVoCountNum();
        case VOSUBCONTRACTACTCLS:
            return getVoSubcontractActCls();
        case SUMAMOUNT:
            return getSumamount();
        case MAKERCODE:
            return getMakerCode();
        case MAKERNAME:
            return getMakerName();
        case CURRENCYCODE:
            return getCurrencyCode();
        case SUPPLIERID:
            return getSupplierId();
        case MAKERID:
            return getMakerId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BEGINNINGCARRYINGOVERID:
            setBeginningCarryingoverId((Number)value);
            return;
        case APPRICABLEPERIODFROM:
            setAppricablePeriodFrom((Date)value);
            return;
        case APPRICABLEPERIODTO:
            setAppricablePeriodTo((Date)value);
            return;
        case VOSTATUS:
            setVoStatus((String)value);
            return;
        case PROCUREMENTGROUPCODE:
            setProcurementGroupCode((String)value);
            return;
        case PROCUREMENTPERSONCODE:
            setProcurementPersonCode((String)value);
            return;
        case SUPPLIERCODE:
            setSupplierCode((String)value);
            return;
        case SUPPLIERNAME:
            setSupplierName((String)value);
            return;
        case VOCOUNTNUM:
            setVoCountNum((String)value);
            return;
        case VOSUBCONTRACTACTCLS:
            setVoSubcontractActCls((String)value);
            return;
        case SUMAMOUNT:
            setSumamount((String)value);
            return;
        case MAKERCODE:
            setMakerCode((String)value);
            return;
        case MAKERNAME:
            setMakerName((String)value);
            return;
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case MAKERID:
            setMakerId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute BeginningCarryingoverId
     */
    public Number getBeginningCarryingoverId() {
        return (Number) getAttributeInternal(BEGINNINGCARRYINGOVERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BeginningCarryingoverId
     */
    public void setBeginningCarryingoverId(Number value) {
        setAttributeInternal(BEGINNINGCARRYINGOVERID, value);
    }

    /**Gets the attribute value for the calculated attribute AppricablePeriodFrom
     */
    public Date getAppricablePeriodFrom() {
        return (Date) getAttributeInternal(APPRICABLEPERIODFROM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AppricablePeriodFrom
     */
    public void setAppricablePeriodFrom(Date value) {
        setAttributeInternal(APPRICABLEPERIODFROM, value);
    }

    /**Gets the attribute value for the calculated attribute AppricablePeriodTo
     */
    public Date getAppricablePeriodTo() {
        return (Date) getAttributeInternal(APPRICABLEPERIODTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AppricablePeriodTo
     */
    public void setAppricablePeriodTo(Date value) {
        setAttributeInternal(APPRICABLEPERIODTO, value);
    }

    /**Gets the attribute value for the calculated attribute VoStatus
     */
    public String getVoStatus() {
        return (String) getAttributeInternal(VOSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoStatus
     */
    public void setVoStatus(String value) {
        setAttributeInternal(VOSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute ProcurementGroupCode
     */
    public String getProcurementGroupCode() {
        return (String) getAttributeInternal(PROCUREMENTGROUPCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProcurementGroupCode
     */
    public void setProcurementGroupCode(String value) {
        setAttributeInternal(PROCUREMENTGROUPCODE, value);
    }

    /**Gets the attribute value for the calculated attribute ProcurementPersonCode
     */
    public String getProcurementPersonCode() {
        return (String) getAttributeInternal(PROCUREMENTPERSONCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProcurementPersonCode
     */
    public void setProcurementPersonCode(String value) {
        setAttributeInternal(PROCUREMENTPERSONCODE, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierCode
     */
    public String getSupplierCode() {
        return (String) getAttributeInternal(SUPPLIERCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierCode
     */
    public void setSupplierCode(String value) {
        setAttributeInternal(SUPPLIERCODE, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierName
     */
    public String getSupplierName() {
        return (String) getAttributeInternal(SUPPLIERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierName
     */
    public void setSupplierName(String value) {
        setAttributeInternal(SUPPLIERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute VoCountNum
     */
    public String getVoCountNum() {
        return (String) getAttributeInternal(VOCOUNTNUM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoCountNum
     */
    public void setVoCountNum(String value) {
        setAttributeInternal(VOCOUNTNUM, value);
    }

    /**Gets the attribute value for the calculated attribute VoSubcontractActCls
     */
    public String getVoSubcontractActCls() {
        return (String) getAttributeInternal(VOSUBCONTRACTACTCLS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoSubcontractActCls
     */
    public void setVoSubcontractActCls(String value) {
        setAttributeInternal(VOSUBCONTRACTACTCLS, value);
    }

    /**Gets the attribute value for the calculated attribute Sumamount
     */
    public String getSumamount() {
        return (String) getAttributeInternal(SUMAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sumamount
     */
    public void setSumamount(String value) {
        setAttributeInternal(SUMAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute MakerCode
     */
    public String getMakerCode() {
        return (String) getAttributeInternal(MAKERCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MakerCode
     */
    public void setMakerCode(String value) {
        setAttributeInternal(MAKERCODE, value);
    }

    /**Gets the attribute value for the calculated attribute MakerName
     */
    public String getMakerName() {
        return (String) getAttributeInternal(MAKERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MakerName
     */
    public void setMakerName(String value) {
        setAttributeInternal(MAKERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierId
     */
    public Number getSupplierId() {
        return (Number) getAttributeInternal(SUPPLIERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierId
     */
    public void setSupplierId(Number value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**Gets the attribute value for the calculated attribute MakerId
     */
    public Number getMakerId() {
        return (Number) getAttributeInternal(MAKERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MakerId
     */
    public void setMakerId(Number value) {
        setAttributeInternal(MAKERID, value);
    }
}
