package train.oracle.apps.ak.ak18726.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class test1VORowImpl extends OAViewRowImpl {
    public static final int LOOKUPTYPE = 0;
    public static final int LOOKUPCODE = 1;
    public static final int MEANING = 2;
    public static final int BEGINNINGCARRYINGOVERID = 3;
    public static final int VOSTATUS = 4;
    public static final int VOORIGININSTRUCTREREQ = 5;
    public static final int PROCUREMENTGROUPCODE = 6;
    public static final int PROCUREMENTPERSONCODE = 7;
    public static final int SUPPLIERID = 8;
    public static final int MAKERID = 9;
    public static final int SUPPLIERCODE = 10;
    public static final int SUPPLIERNAME = 11;
    public static final int VOSUBCONTRACTACTCLS = 12;
    public static final int MAKERCODE = 13;
    public static final int MAKERNAME = 14;
    public static final int COUNTNUM = 15;
    public static final int MONTHSPURCHASEPRICE6 = 16;
    public static final int APPRICABLEPERIODFROM = 17;
    public static final int APPRICABLEPERIODTO = 18;
    public static final int STATUS = 19;
    public static final int YITEMNO = 20;
    public static final int CURRENCYCODE = 21;
    public static final int TLAPPRERIMPLFNDUSERID = 22;
    public static final int GMAPPRERIMPLFNDUSERID = 23;
    public static final int TLAPPROVALSTATUS = 24;
    public static final int GMAPPROVALSTATUS = 25;
    public static final int TLAPPROVERFNDUSERID = 26;
    public static final int GMAPPROVERFNDUSERID = 27;
    public static final int VOTLUSER = 28;
    public static final int VOTLIMPLUSER = 29;
    public static final int VOTLAPPROVALSTATUS = 30;
    public static final int TLAPPROVALDATE = 31;
    public static final int VOGMUSER = 32;
    public static final int VOGMIMPLUSER = 33;
    public static final int VOGMAPPROVALSTATUS = 34;
    public static final int SELECTION = 35;
    public static final int GMAPPROVALDATE = 36;
    public static final int WORKFLOWSERIALNO = 37;
    public static final int ORGID = 38;
    public static final int OBJECTVERSIONNUMBER = 39;
    public static final int CREATEDBY = 40;
    public static final int CREATIONDATE = 41;
    public static final int LASTUPDATEDBY = 42;
    public static final int LASTUPDATEDATE = 43;
    public static final int LASTUPDATELOGIN = 44;
    public static final int REQUESTID = 45;
    public static final int PROGRAMAPPLICATIONID = 46;
    public static final int PROGRAMID = 47;
    public static final int PROGRAMUPDATEDATE = 48;

    /**This is the default constructor (do not remove)
     */
    public test1VORowImpl() {
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LOOKUPTYPE:
            return getLookupType();
        case LOOKUPCODE:
            return getLookupCode();
        case MEANING:
            return getMeaning();
        case BEGINNINGCARRYINGOVERID:
            return getBeginningCarryingoverId();
        case VOSTATUS:
            return getVoStatus();
        case VOORIGININSTRUCTREREQ:
            return getVoOriginInstructReReq();
        case PROCUREMENTGROUPCODE:
            return getProcurementGroupCode();
        case PROCUREMENTPERSONCODE:
            return getProcurementPersonCode();
        case SUPPLIERID:
            return getSupplierId();
        case MAKERID:
            return getMakerId();
        case SUPPLIERCODE:
            return getSupplierCode();
        case SUPPLIERNAME:
            return getSupplierName();
        case VOSUBCONTRACTACTCLS:
            return getVoSubcontractActCls();
        case MAKERCODE:
            return getMakerCode();
        case MAKERNAME:
            return getMakerName();
        case COUNTNUM:
            return getCountNum();
        case MONTHSPURCHASEPRICE6:
            return getMonthsPurchasePrice6();
        case APPRICABLEPERIODFROM:
            return getAppricablePeriodFrom();
        case APPRICABLEPERIODTO:
            return getAppricablePeriodTo();
        case STATUS:
            return getStatus();
        case YITEMNO:
            return getYItemNo();
        case CURRENCYCODE:
            return getCurrencyCode();
        case TLAPPRERIMPLFNDUSERID:
            return getTlApprerImplFndUserId();
        case GMAPPRERIMPLFNDUSERID:
            return getGmApprerImplFndUserId();
        case TLAPPROVALSTATUS:
            return getTlApprovalStatus();
        case GMAPPROVALSTATUS:
            return getGmApprovalStatus();
        case TLAPPROVERFNDUSERID:
            return getTlApproverFndUserId();
        case GMAPPROVERFNDUSERID:
            return getGmApproverFndUserId();
        case VOTLUSER:
            return getVoTlUser();
        case VOTLIMPLUSER:
            return getVoTlImplUser();
        case VOTLAPPROVALSTATUS:
            return getVoTlApprovalStatus();
        case TLAPPROVALDATE:
            return getTlApprovalDate();
        case VOGMUSER:
            return getVoGmUser();
        case VOGMIMPLUSER:
            return getVoGmImplUser();
        case VOGMAPPROVALSTATUS:
            return getVoGmApprovalStatus();
        case SELECTION:
            return getSelection();
        case GMAPPROVALDATE:
            return getGmApprovalDate();
        case WORKFLOWSERIALNO:
            return getWorkflowSerialNo();
        case ORGID:
            return getOrgId();
        case OBJECTVERSIONNUMBER:
            return getObjectVersionNumber();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case REQUESTID:
            return getRequestId();
        case PROGRAMAPPLICATIONID:
            return getProgramApplicationId();
        case PROGRAMID:
            return getProgramId();
        case PROGRAMUPDATEDATE:
            return getProgramUpdateDate();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LOOKUPTYPE:
            setLookupType((String)value);
            return;
        case LOOKUPCODE:
            setLookupCode((String)value);
            return;
        case MEANING:
            setMeaning((String)value);
            return;
        case BEGINNINGCARRYINGOVERID:
            setBeginningCarryingoverId((Number)value);
            return;
        case VOSTATUS:
            setVoStatus((String)value);
            return;
        case VOORIGININSTRUCTREREQ:
            setVoOriginInstructReReq((String)value);
            return;
        case PROCUREMENTGROUPCODE:
            setProcurementGroupCode((String)value);
            return;
        case PROCUREMENTPERSONCODE:
            setProcurementPersonCode((String)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case MAKERID:
            setMakerId((Number)value);
            return;
        case SUPPLIERCODE:
            setSupplierCode((String)value);
            return;
        case SUPPLIERNAME:
            setSupplierName((String)value);
            return;
        case VOSUBCONTRACTACTCLS:
            setVoSubcontractActCls((String)value);
            return;
        case MAKERCODE:
            setMakerCode((String)value);
            return;
        case MAKERNAME:
            setMakerName((String)value);
            return;
        case COUNTNUM:
            setCountNum((Number)value);
            return;
        case MONTHSPURCHASEPRICE6:
            setMonthsPurchasePrice6((Number)value);
            return;
        case APPRICABLEPERIODFROM:
            setAppricablePeriodFrom((Date)value);
            return;
        case APPRICABLEPERIODTO:
            setAppricablePeriodTo((Date)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case YITEMNO:
            setYItemNo((String)value);
            return;
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        case TLAPPRERIMPLFNDUSERID:
            setTlApprerImplFndUserId((Number)value);
            return;
        case GMAPPRERIMPLFNDUSERID:
            setGmApprerImplFndUserId((Number)value);
            return;
        case TLAPPROVALSTATUS:
            setTlApprovalStatus((String)value);
            return;
        case GMAPPROVALSTATUS:
            setGmApprovalStatus((String)value);
            return;
        case TLAPPROVERFNDUSERID:
            setTlApproverFndUserId((Number)value);
            return;
        case GMAPPROVERFNDUSERID:
            setGmApproverFndUserId((Number)value);
            return;
        case VOTLUSER:
            setVoTlUser((String)value);
            return;
        case VOTLIMPLUSER:
            setVoTlImplUser((String)value);
            return;
        case VOTLAPPROVALSTATUS:
            setVoTlApprovalStatus((String)value);
            return;
        case TLAPPROVALDATE:
            setTlApprovalDate((Date)value);
            return;
        case VOGMUSER:
            setVoGmUser((String)value);
            return;
        case VOGMIMPLUSER:
            setVoGmImplUser((String)value);
            return;
        case VOGMAPPROVALSTATUS:
            setVoGmApprovalStatus((String)value);
            return;
        case SELECTION:
            setSelection((String)value);
            return;
        case GMAPPROVALDATE:
            setGmApprovalDate((Date)value);
            return;
        case WORKFLOWSERIALNO:
            setWorkflowSerialNo((Number)value);
            return;
        case ORGID:
            setOrgId((Number)value);
            return;
        case OBJECTVERSIONNUMBER:
            setObjectVersionNumber((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case REQUESTID:
            setRequestId((Number)value);
            return;
        case PROGRAMAPPLICATIONID:
            setProgramApplicationId((Number)value);
            return;
        case PROGRAMID:
            setProgramId((Number)value);
            return;
        case PROGRAMUPDATEDATE:
            setProgramUpdateDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute LookupType
     */
    public String getLookupType() {
        return (String) getAttributeInternal(LOOKUPTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LookupType
     */
    public void setLookupType(String value) {
        setAttributeInternal(LOOKUPTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute LookupCode
     */
    public String getLookupCode() {
        return (String) getAttributeInternal(LOOKUPCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LookupCode
     */
    public void setLookupCode(String value) {
        setAttributeInternal(LOOKUPCODE, value);
    }

    /**Gets the attribute value for the calculated attribute Meaning
     */
    public String getMeaning() {
        return (String) getAttributeInternal(MEANING);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Meaning
     */
    public void setMeaning(String value) {
        setAttributeInternal(MEANING, value);
    }

    /**Gets the attribute value for the calculated attribute BeginningCarryingoverId
     */
    public Number getBeginningCarryingoverId() {
        return (Number) getAttributeInternal(BEGINNINGCARRYINGOVERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BeginningCarryingoverId
     */
    public void setBeginningCarryingoverId(Number value) {
        setAttributeInternal(BEGINNINGCARRYINGOVERID, value);
    }

    /**Gets the attribute value for the calculated attribute VoStatus
     */
    public String getVoStatus() {
        return (String) getAttributeInternal(VOSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoStatus
     */
    public void setVoStatus(String value) {
        setAttributeInternal(VOSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute VoOriginInstructReReq
     */
    public String getVoOriginInstructReReq() {
        return (String) getAttributeInternal(VOORIGININSTRUCTREREQ);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoOriginInstructReReq
     */
    public void setVoOriginInstructReReq(String value) {
        setAttributeInternal(VOORIGININSTRUCTREREQ, value);
    }

    /**Gets the attribute value for the calculated attribute ProcurementGroupCode
     */
    public String getProcurementGroupCode() {
        return (String) getAttributeInternal(PROCUREMENTGROUPCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProcurementGroupCode
     */
    public void setProcurementGroupCode(String value) {
        setAttributeInternal(PROCUREMENTGROUPCODE, value);
    }

    /**Gets the attribute value for the calculated attribute ProcurementPersonCode
     */
    public String getProcurementPersonCode() {
        return (String) getAttributeInternal(PROCUREMENTPERSONCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProcurementPersonCode
     */
    public void setProcurementPersonCode(String value) {
        setAttributeInternal(PROCUREMENTPERSONCODE, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierId
     */
    public Number getSupplierId() {
        return (Number) getAttributeInternal(SUPPLIERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierId
     */
    public void setSupplierId(Number value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**Gets the attribute value for the calculated attribute MakerId
     */
    public Number getMakerId() {
        return (Number) getAttributeInternal(MAKERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MakerId
     */
    public void setMakerId(Number value) {
        setAttributeInternal(MAKERID, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierCode
     */
    public String getSupplierCode() {
        return (String) getAttributeInternal(SUPPLIERCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierCode
     */
    public void setSupplierCode(String value) {
        setAttributeInternal(SUPPLIERCODE, value);
    }

    /**Gets the attribute value for the calculated attribute SupplierName
     */
    public String getSupplierName() {
        return (String) getAttributeInternal(SUPPLIERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupplierName
     */
    public void setSupplierName(String value) {
        setAttributeInternal(SUPPLIERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute VoSubcontractActCls
     */
    public String getVoSubcontractActCls() {
        return (String) getAttributeInternal(VOSUBCONTRACTACTCLS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoSubcontractActCls
     */
    public void setVoSubcontractActCls(String value) {
        setAttributeInternal(VOSUBCONTRACTACTCLS, value);
    }

    /**Gets the attribute value for the calculated attribute MakerCode
     */
    public String getMakerCode() {
        return (String) getAttributeInternal(MAKERCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MakerCode
     */
    public void setMakerCode(String value) {
        setAttributeInternal(MAKERCODE, value);
    }

    /**Gets the attribute value for the calculated attribute MakerName
     */
    public String getMakerName() {
        return (String) getAttributeInternal(MAKERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MakerName
     */
    public void setMakerName(String value) {
        setAttributeInternal(MAKERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute CountNum
     */
    public Number getCountNum() {
        return (Number) getAttributeInternal(COUNTNUM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CountNum
     */
    public void setCountNum(Number value) {
        setAttributeInternal(COUNTNUM, value);
    }

    /**Gets the attribute value for the calculated attribute MonthsPurchasePrice6
     */
    public Number getMonthsPurchasePrice6() {
        return (Number) getAttributeInternal(MONTHSPURCHASEPRICE6);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MonthsPurchasePrice6
     */
    public void setMonthsPurchasePrice6(Number value) {
        setAttributeInternal(MONTHSPURCHASEPRICE6, value);
    }

    /**Gets the attribute value for the calculated attribute AppricablePeriodFrom
     */
    public Date getAppricablePeriodFrom() {
        return (Date) getAttributeInternal(APPRICABLEPERIODFROM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AppricablePeriodFrom
     */
    public void setAppricablePeriodFrom(Date value) {
        setAttributeInternal(APPRICABLEPERIODFROM, value);
    }

    /**Gets the attribute value for the calculated attribute AppricablePeriodTo
     */
    public Date getAppricablePeriodTo() {
        return (Date) getAttributeInternal(APPRICABLEPERIODTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AppricablePeriodTo
     */
    public void setAppricablePeriodTo(Date value) {
        setAttributeInternal(APPRICABLEPERIODTO, value);
    }

    /**Gets the attribute value for the calculated attribute Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for the calculated attribute YItemNo
     */
    public String getYItemNo() {
        return (String) getAttributeInternal(YITEMNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute YItemNo
     */
    public void setYItemNo(String value) {
        setAttributeInternal(YITEMNO, value);
    }

    /**Gets the attribute value for the calculated attribute CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**Gets the attribute value for the calculated attribute TlApprerImplFndUserId
     */
    public Number getTlApprerImplFndUserId() {
        return (Number) getAttributeInternal(TLAPPRERIMPLFNDUSERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TlApprerImplFndUserId
     */
    public void setTlApprerImplFndUserId(Number value) {
        setAttributeInternal(TLAPPRERIMPLFNDUSERID, value);
    }

    /**Gets the attribute value for the calculated attribute GmApprerImplFndUserId
     */
    public Number getGmApprerImplFndUserId() {
        return (Number) getAttributeInternal(GMAPPRERIMPLFNDUSERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute GmApprerImplFndUserId
     */
    public void setGmApprerImplFndUserId(Number value) {
        setAttributeInternal(GMAPPRERIMPLFNDUSERID, value);
    }

    /**Gets the attribute value for the calculated attribute TlApprovalStatus
     */
    public String getTlApprovalStatus() {
        return (String) getAttributeInternal(TLAPPROVALSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TlApprovalStatus
     */
    public void setTlApprovalStatus(String value) {
        setAttributeInternal(TLAPPROVALSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute GmApprovalStatus
     */
    public String getGmApprovalStatus() {
        return (String) getAttributeInternal(GMAPPROVALSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute GmApprovalStatus
     */
    public void setGmApprovalStatus(String value) {
        setAttributeInternal(GMAPPROVALSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute TlApproverFndUserId
     */
    public Number getTlApproverFndUserId() {
        return (Number) getAttributeInternal(TLAPPROVERFNDUSERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TlApproverFndUserId
     */
    public void setTlApproverFndUserId(Number value) {
        setAttributeInternal(TLAPPROVERFNDUSERID, value);
    }

    /**Gets the attribute value for the calculated attribute GmApproverFndUserId
     */
    public Number getGmApproverFndUserId() {
        return (Number) getAttributeInternal(GMAPPROVERFNDUSERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute GmApproverFndUserId
     */
    public void setGmApproverFndUserId(Number value) {
        setAttributeInternal(GMAPPROVERFNDUSERID, value);
    }

    /**Gets the attribute value for the calculated attribute VoTlUser
     */
    public String getVoTlUser() {
        return (String) getAttributeInternal(VOTLUSER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoTlUser
     */
    public void setVoTlUser(String value) {
        setAttributeInternal(VOTLUSER, value);
    }

    /**Gets the attribute value for the calculated attribute VoTlImplUser
     */
    public String getVoTlImplUser() {
        return (String) getAttributeInternal(VOTLIMPLUSER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoTlImplUser
     */
    public void setVoTlImplUser(String value) {
        setAttributeInternal(VOTLIMPLUSER, value);
    }

    /**Gets the attribute value for the calculated attribute VoTlApprovalStatus
     */
    public String getVoTlApprovalStatus() {
        return (String) getAttributeInternal(VOTLAPPROVALSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoTlApprovalStatus
     */
    public void setVoTlApprovalStatus(String value) {
        setAttributeInternal(VOTLAPPROVALSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute TlApprovalDate
     */
    public Date getTlApprovalDate() {
        return (Date) getAttributeInternal(TLAPPROVALDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TlApprovalDate
     */
    public void setTlApprovalDate(Date value) {
        setAttributeInternal(TLAPPROVALDATE, value);
    }

    /**Gets the attribute value for the calculated attribute VoGmUser
     */
    public String getVoGmUser() {
        return (String) getAttributeInternal(VOGMUSER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoGmUser
     */
    public void setVoGmUser(String value) {
        setAttributeInternal(VOGMUSER, value);
    }

    /**Gets the attribute value for the calculated attribute VoGmImplUser
     */
    public String getVoGmImplUser() {
        return (String) getAttributeInternal(VOGMIMPLUSER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoGmImplUser
     */
    public void setVoGmImplUser(String value) {
        setAttributeInternal(VOGMIMPLUSER, value);
    }

    /**Gets the attribute value for the calculated attribute VoGmApprovalStatus
     */
    public String getVoGmApprovalStatus() {
        return (String) getAttributeInternal(VOGMAPPROVALSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VoGmApprovalStatus
     */
    public void setVoGmApprovalStatus(String value) {
        setAttributeInternal(VOGMAPPROVALSTATUS, value);
    }

    /**Gets the attribute value for the calculated attribute Selection
     */
    public String getSelection() {
        return (String) getAttributeInternal(SELECTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Selection
     */
    public void setSelection(String value) {
        setAttributeInternal(SELECTION, value);
    }

    /**Gets the attribute value for the calculated attribute GmApprovalDate
     */
    public Date getGmApprovalDate() {
        return (Date) getAttributeInternal(GMAPPROVALDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute GmApprovalDate
     */
    public void setGmApprovalDate(Date value) {
        setAttributeInternal(GMAPPROVALDATE, value);
    }

    /**Gets the attribute value for the calculated attribute WorkflowSerialNo
     */
    public Number getWorkflowSerialNo() {
        return (Number) getAttributeInternal(WORKFLOWSERIALNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WorkflowSerialNo
     */
    public void setWorkflowSerialNo(Number value) {
        setAttributeInternal(WORKFLOWSERIALNO, value);
    }

    /**Gets the attribute value for the calculated attribute OrgId
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the attribute value for the calculated attribute ObjectVersionNumber
     */
    public Number getObjectVersionNumber() {
        return (Number) getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ObjectVersionNumber
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute RequestId
     */
    public Number getRequestId() {
        return (Number) getAttributeInternal(REQUESTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RequestId
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**Gets the attribute value for the calculated attribute ProgramApplicationId
     */
    public Number getProgramApplicationId() {
        return (Number) getAttributeInternal(PROGRAMAPPLICATIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProgramApplicationId
     */
    public void setProgramApplicationId(Number value) {
        setAttributeInternal(PROGRAMAPPLICATIONID, value);
    }

    /**Gets the attribute value for the calculated attribute ProgramId
     */
    public Number getProgramId() {
        return (Number) getAttributeInternal(PROGRAMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProgramId
     */
    public void setProgramId(Number value) {
        setAttributeInternal(PROGRAMID, value);
    }

    /**Gets the attribute value for the calculated attribute ProgramUpdateDate
     */
    public Date getProgramUpdateDate() {
        return (Date) getAttributeInternal(PROGRAMUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProgramUpdateDate
     */
    public void setProgramUpdateDate(Date value) {
        setAttributeInternal(PROGRAMUPDATEDATE, value);
    }
}
